### ISSUE TITLE
followers list should come

### ISSUE THREAD

**Issue by VishakhaAwasthi01** [MeghalBisht/Gamergram#13]
when we are on someone's profile, we should be able to see the list of there followers, when clicking on followers

**Comment by MeghalBisht** [comment]
Hey @VishakhaAwasthi01 , that's a good idea, I was thinking about it too! :) You can go ahead and give it a shot, I'll assign you

**Comment by VishakhaAwasthi01** [comment]
Sure, thanks :)

**Comment by yafiwebdev** [comment]
@MeghalBisht Hey, is this still open or what?

**Comment by MeghalBisht** [comment]
@yafiwebdev Yep, you can go ahead!

**Comment by yafiwebdev** [comment]
There are many npm issues while trying to set it up locally, unfortunately I don't have enough time to solve them..

**Comment by MeghalBisht** [comment]
Duplicate of #3
