### ISSUE TITLE
posts should be aligned

### ISSUE THREAD

**Issue by VishakhaAwasthi01** [MeghalBisht/Gamergram#14]
while visiting profiles I noticed, posts are not aligned properly, also they can have some border of the site's theme colour

**Comment by ranjitkshah** [comment]
> while visiting profiles I noticed, posts are not aligned properly, also they can have some border of the site's theme colour

Not aligned properly?? in what way

**Comment by MeghalBisht** [comment]
@VishakhaAwasthi01  yeah! The alignment is a issue, I want someone to redesign the entire profile's page. If you want to take this up, go ahead!

**Comment by VishakhaAwasthi01** [comment]
sure, thanks :)

**Comment by VishakhaAwasthi01** [comment]
getting this issue Proxy error: Could not proxy request /signin from localhost:3000 to http://localhost:5000 (ECONNREFUSED).
Not able to sign in

**Comment by MeghalBisht** [comment]
> gnin from lo

Hey, did you install all the dependencies correctly?  This looks more like a cors error to me. When I try to run the app, it works fine!

**Comment by MeghalBisht** [comment]
> getting this issue Proxy error: Could not proxy request /signin from localhost:3000 to http://localhost:5000 (ECONNREFUSED).
> Not able to sign in

Hey, did you install all the dependencies correctly? This looks more like a cors error to me. When I try to run the app, it works fine!
