### ISSUE TITLE
Add the time at which the post was submitted.

### ISSUE THREAD

**Issue by MeghalBisht** [MeghalBisht/Gamergram#2]
**Add time at which the post was made.**
1. If it was posted less than 2 mins ago, then display "posted a few minutes ago"
else
2. Add the time, following the given format -
**_FORMAT_** 
- Posted x minutes ago
-Posted y hours ago
-Posted z days ago
-Posted x' years ago

**Add the date at the place of black box marked in the picture**
Please add a screenshot for the same in your PR.
For any confusions/queries comment below.

![2020-10-12 (9)](https://user-images.githubusercontent.com/61330148/95776982-f48dad80-0ce2-11eb-8346-829ba8719a8e.png)

**Comment by matteoauger** [comment]
Hello, can I work on it ? :)

**Comment by hexifox** [comment]
Hi @MeghalBisht, would it be possible for me to have a look at his issue?

**Comment by MeghalBisht** [comment]
@matteoauger  Sure! :)

**Comment by MeghalBisht** [comment]
@hexifox  Yes you can! I will assign you too

**Comment by MeghalBisht** [comment]
Hey @matteoauger , this looks awesome! Thanks a lot 👍
