### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by MeghalBisht** [MeghalBisht/Gamergram#3]
**Add a footer component.**

The footer should be as described in the picture, however the color scheme should be according to the project.
Refer client/src/App.css to see the root colors.

Create a Footer.js in client/src/Components.
Footer should always be at the bottom and in all the pages, add it to the main App.js component.

Important : Currently, the footer is only visible in login/signup screens. You can delete that one and add same Footer throughout the project. (Access it in : client/src/Components/Screens/Footer.js)

For styling, create a new css file (client/src/Styles/Footer.css)

**Important** : **Attach a screenshot with the PR.**

![images](https://user-images.githubusercontent.com/61330148/95777699-51d62e80-0ce4-11eb-9a21-e1040fd02374.png)

**Comment by bineetNaidu** [comment]
I would love to contribute onto this project . feel free to assign me this task.

**Comment by MeghalBisht** [comment]
Sure go ahead!

**Comment by bineetNaidu** [comment]
Thanks for assigning me this project.

**Comment by bineetNaidu** [comment]
in this we need ENV's  but i have got none

**Comment by MeghalBisht** [comment]
@bineetNaidu  To add the footer, you don't need any env.

**Comment by kimhluu** [comment]
Can I contribute? Please assign me

**Comment by MeghalBisht** [comment]
Hey, @kimhluu! Currently, @bineetNaidu is working on it! If he backs off I will assign it to you :)

**Comment by bineetNaidu** [comment]
within 30 min i will send a PR

**Comment by MeghalBisht** [comment]
@bineetNaidu Yes take your time! No hurries. :)
