### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by MeghalBisht** [MeghalBisht/Gamergram#4]
**Add pagination in the Home Page.**

Display only 5 posts and then add a **load more button** to show the other posts.

Important : **Add a screenshot with the PR.**

All posts are displayed in the **Home Component**. (client/src/Components/Screens/Home.js) (line number : 178)

**Comment by shubheshdwivedi** [comment]
Hi, can I work on this?

**Comment by SimoSultan** [comment]
Also happy to do this too.

**Comment by bhantsi** [comment]
I can do this

**Comment by MeghalBisht** [comment]
Hey, @shubheshdwivedi Yes please go on!

**Comment by MeghalBisht** [comment]
Hey @SimoSultan , @bhantsi. Please wait, if he backs off I will assign it to you both! :)

**Comment by shubheshdwivedi** [comment]
I have raised the PR, kindly review it.

**Comment by MeghalBisht** [comment]
One issue I can see is that once you click on load more posts, the next posts (let say 5 are displayed) but the last image(from these 5 images) come first. I will reopen the issue, if you would like to improve you can again raise a pull. Thanks :)

Refer pull #12 

@bhantsi @SimoSultan If you want to work on this let me know I'll assign, the task is reduced now :)
