### ISSUE TITLE
Add Contributors Page

### ISSUE THREAD

**Issue by MeghalBisht** [MeghalBisht/Gamergram#7]
Add a Contributors Page by creating a file in client/src/Components/Screens/Contributors.js.

**# What has to be done?**

**Add a new route with /contributors (client/src/App.js).**

1. In this page, display the **names and pictures** of all the contributors. (take dummy data for now)
2. Add a **link to their github profiles**.
3. A **link to their pull requests.**
4. Use **flexbox/grid and make it responsive**
5. **Follow the color theme** of the entire app. (check cleint/src/App.css to see the color scheme)
6. The link for this page, should be in the footer component (client/src/Components/Footer)

**IMPORTANT : Please attach screenshot/video-recording for the changes made**

**Comment by EnechukwuChibuike** [comment]
> Add a Contributors Page by creating a file in client/src/Components/Screens/Contributors.js.
> 
> **# What has to be done?**
> 
> **Add a new route with /contributors (client/src/App.js).**
> 
>     1. In this page, display the **names and pictures** of all the contributors. (take dummy data for now)
> 
>     2. Add a **link to their github profiles**.
> 
>     3. A **link to their pull requests.**
> 
>     4. Use **flexbox/grid and make it responsive**
> 
>     5. **Follow the color theme** of the entire app. (check cleint/src/App.css to see the color scheme)
> 
>     6. The link for this page, should be in the footer component (client/src/Components/Footer)
> 
> 
> **IMPORTANT : Please attach screenshot/video-recording for the changes made**

What do you mean by a link to their pull request?

**Comment by ranjitkshah** [comment]
> > Add a Contributors Page by creating a file in client/src/Components/Screens/Contributors.js.
> > **# What has to be done?**
> > **Add a new route with /contributors (client/src/App.js).**
> > ```
> > 1. In this page, display the **names and pictures** of all the contributors. (take dummy data for now)
> > 
> > 2. Add a **link to their github profiles**.
> > 
> > 3. A **link to their pull requests.**
> > 
> > 4. Use **flexbox/grid and make it responsive**
> > 
> > 5. **Follow the color theme** of the entire app. (check cleint/src/App.css to see the color scheme)
> > 
> > 6. The link for this page, should be in the footer component (client/src/Components/Footer)
> > ```
> > 
> > 
> > **IMPORTANT : Please attach screenshot/video-recording for the changes made**
> 
> What do you mean by a link to their pull request?

it means just provide a button which have href tag to "what changes he contributed/committed"

**Comment by EnechukwuChibuike** [comment]
> > > Add a Contributors Page by creating a file in client/src/Components/Screens/Contributors.js.
> > > **# What has to be done?**
> > > **Add a new route with /contributors (client/src/App.js).**
> > > ```
> > > 1. In this page, display the **names and pictures** of all the contributors. (take dummy data for now)
> > > 
> > > 2. Add a **link to their github profiles**.
> > > 
> > > 3. A **link to their pull requests.**
> > > 
> > > 4. Use **flexbox/grid and make it responsive**
> > > 
> > > 5. **Follow the color theme** of the entire app. (check cleint/src/App.css to see the color scheme)
> > > 
> > > 6. The link for this page, should be in the footer component (client/src/Components/Footer)
> > > ```
> > > 
> > > 
> > > **IMPORTANT : Please attach screenshot/video-recording for the changes made**
> > 
> > 
> > What do you mean by a link to their pull request?
> 
> it means just provide a button which have href tag to "what changes he contributed/committed"

Okay
I will do it

**Comment by MeghalBisht** [comment]
Hey @EnechukwuChibuike , I am assigning you! For any queries please ask!

**Comment by EnechukwuChibuike** [comment]
> Hey @EnechukwuChibuike , I am assigning you! For any queries please ask!

Ok

**Comment by Aayush-Bhatt** [comment]
can I work on this

**Comment by EnechukwuChibuike** [comment]
> Hey @EnechukwuChibuike , I am assigning you! For any queries please ask!

@MeghalBisht you said that I should use Flexbox/Grid for responsiveness
That means no framework right?

**Comment by EnechukwuChibuike** [comment]
Link to the github will also be a button right?

**Comment by EnechukwuChibuike** [comment]
OK

> @EnechukwuChibuike You can use a framework, infact materialize is being used in this project.
> **But I want the same theme to be followed throughout the App.**
> Also, for one page I dont think we need a separate framework!
> And yes, link to github will be a button. (check login/signup button something like that)

ok
