### ISSUE TITLE
Design Enhancement

### ISSUE THREAD

**Issue by MeghalBisht** [MeghalBisht/Gamergram#9]
## **This issue is aimed to improve the Design of the App.**

#Feel free to bring up your ideas.
**Multiple PRs are allowed and will be merged.**

## Suggestions-
1. Add a customize theme button, and add different color themes (just like in twitter).
The current color scheme can be accessed from ( client/src/App.css )

**For any other issue apart from design, please consider opening an issue!**

## **IMPORTANT : Please don't make a PR for minor changes (white space removal, spelling error etc)**

**Comment by tranjenny** [comment]
How to run your application? I get an 
`Error message: Cannot find module './dev'.`
 What have you added to the dev directory?

**Comment by MeghalBisht** [comment]
Hey @tranjenny, they are just keys used for the email service, mongoURI and stuff.

**You can run the app with node app.js
then, cd client and then npm start.**

You can also comment out ./dev import if still issue persists 
**OR**
Don't start server as only design enhancement is needed.

Drop a comment if you face more issues! 👍

**Comment by bruceyboy86** [comment]
@MeghalBisht I'm building a theme button

**Comment by MeghalBisht** [comment]
Hey @bruceyboy86 thanks! :) I am assigning you.
